#!/usr/bin/env bash
EXE=$(which nvim)

if test -f "$EXE"; then
  pushd $HOME/opts/neovim/
  git fetch; git merge 
  sudo rm -rf .deps
  make -j2
  sudo make install
  popd
else 
  pushd $HOME/opts/ 
  gh repo clone neovim/neovim -- --depth 1
  pushd neovim

  sudo apt-get install ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen -y

  make -j2
  sudo make install

  popd; popd
fi
