#!/usr/bin/env bash
EXE=$(which npm)

if test -f "$EXE"; then
  sudo apt update 
else 
  pushd $HOME/opts/
  wget https://nodejs.org/dist/v16.14.2/node-v16.14.2-linux-x64.tar.xz
  tar xvf node-v16.14.2-linux-x64.tar.xz
  mv node-v16.14.2-linux-x64 node
  popd
fi

printf "Put this piece of script in /etc/environment file:\n\n"
printf "PATH=\"/home/<username>/opts/node/bin/:\$PATH\"\n\n"
printf "Then run 'source /etc/environment', or better log out and log back in.\n"
printf "Now node and npm should be installed!!!"
