#!/usr/bin/env bash
EXE=$(which nvim)

if test -f "$EXE"; then
  pushd $HOME/opts/neovim/
  git fetch; git merge 
  sudo rm -rf .deps
  sudo make install
  popd
else 
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
  sudo apt update
  sudo apt install gh -y
fi
