#!/usr/bin/env bash
EXE=$(which exa)

pushd $HOME/opts/
rm -rf exa-linux-x86_64-v0.10.1.zip
wget https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip
rm -rf exa
mkdir exa; cd exa
unzip ../exa-linux-x86_64-v0.10.1.zip
popd

printf "Put this piece of script at the end of /etc/profile:\n\n"
printf "export PATH=\"/home/<username>/opts/exa/bin/:\$PATH\"\n\n"
printf "Then run 'source /etc/profile', or better log out and log back in.\n"
printf "Now node and npm should be installed!!!\n"
