#!/usr/bin/env bash
EXE=$(which go)

DEP="wget"

sudo apt install $DEP -y

if test -f "$EXE"; then
  pushd $HOME/.scripts/
  ./go_installer && rm $HOME/.bash_profile
  popd
else 
  pushd $HOME/.scripts/
  wget https://get.golang.org/$(uname)/go_installer && chmod a+x go_installer && ./go_installer && rm $HOME/.bash_profile
  popd
fi
