#!/usr/bin/env bash
EXE=$(which vagrant)

if test -f "$EXE"; then
  sudo apt update 
  sudo apt install vagrant -y
else 
  curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" -y
  sudo apt update && sudo apt install vagrant -y 
fi
