#!/usr/bin/env bash
EXE=$(which wezterm)

pushd $HOME/opts/
curl -LO https://github.com/TheAssassin/AppImageLauncher/releases/download/v2.2.0/appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb
sudo apt install -y ./appimagelauncher_2.2.0-travis995.0f91801.bionic_amd64.deb 
popd
