
[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[font]
size = 10

[font.bold]
family = "MartianMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "MartianMono Nerd Font"
style = "Italic"

[font.normal]
family = "MartianMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 5

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 0.9

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 10
y = 10

[env]
TERM = "xterm-256color"

[general]
import = ["/home/ritux/.config/alacritty/everforest.toml"]
