#!/bin/sh

lock='gtklock'

if pgrep -x 'swayidle'; then
    pkill swayidle
fi

swayidle -w \
    timeout 400 "$lock" \
    timeout 1200 'sudo systemctl suspend' \
    before-sleep "$lock; sleep 1" \
    after-resume 'swaymsg "output * dpms on"' &
