#!/bin/sh

if pgrep -x "swayidle"; then
    pkill swayidle
fi

swayidle -w \
    timeout 400 'swaylock' \
    timeout 1200 'sudo systemctl suspend' \
    before-sleep 'swaylock; sleep 1' \
    after-resume 'swaymsg "output * dpms on"' &
