#!/bin/sh
# Original author: Luke Smith

# The famous "get a menu of emojis to copy" script.

# Get user selection via a menu from emoji file.
# This $DMENU environment variable needs to be 
# configured by the user, if they want to make this
# script work.
chosen=$(cut -d ';' -f1 ~/emoji | $DMENU  | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
	ydotool type "$chosen"
else
	printf "%s" "$chosen" | $CLIP
	notify-send "'$chosen' copied to clipboard." &
fi
