[tools]
"github:cli/cli" = "latest"
"github:neovim/neovim" = "latest"
zig = "latest"
"github:zed-industries/zed" = "latest"
go = "latest"
rust = "latest"
cargo-binstall = "latest"
"cargo:stylua" = "latest"
"cargo:selene" = "latest"
"cargo:starship" = "latest"
"cargo:tree-sitter-cli" = "latest"
cmake = "latest"
python = "latest"
"pipx:trash-cli" = "latest"
"cargo:just" = "latest"
node = "latest"
"cargo:zellij" = "latest"

[settings.cargo]
binstall = true

